[package]
name = "rust-actix-docker"
version = "0.1.0"
authors = [""]

[dependencies]
actix-web = "0.7.6"
actix = "0.7.4"

serde = "1.0.78"
serde_json = "1.0.27"
serde_derive = "1.0.78"
json = "0.11.13"
